algo = input("Digite algo: ")
print('O tipo primitico desse valor é: {}'.format(type(algo)))
print('{} é numero? {}'.format(algo,algo.isnumeric()))
print('{} é alfabetico? {}'.format(algo,algo.isalpha()))
print('{} é numerico ou alfabetico? {}'.format(algo,algo.isalnum()))
print('{} é tudo maiusculo {}'.format(algo,algo.isupper()))
print('{} é tudo minusculo? {}'.format(algo,algo.islower()))
print('{} tem somente espaços? {}'.format(algo,algo.isspace()))
print('{} esta capitalizada? {}'.format(algo,algo.istitle()))
